#!/bin/sh
BASE=$(dirname $(dirname $(readlink -en $0)))

docker run -it --rm \
	-v "$BASE:/usr/src/geobroker" \
	-v "$BASE/.m2:/root/.m2" \
	-w /usr/src/geobroker \
	maven:alpine mvn \
		"$@" clean package
